#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v0.10.3
    with:
      extension_name: aws
      duckdb_version: '7d684db162df67be1873e80484f764011ec57c1f'
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools' # Doesn't work anyway: env local file or env access possible

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v0.10.3
    secrets: inherit
    with:
      extension_name: aws
      duckdb_version: '7d684db162df67be1873e80484f764011ec57c1f'
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads;windows_amd64_rtools' # Doesn't work anyway: env local file or env access possible